### ISSUE TITLE
Monkey中参数s后的数值需要随机生成

### ISSUE THREAD

**Issue by xianshancom** [alibaba/mobileperf#1]
1.每次执行-s后的数值需要随机产生，以起到伪随机数的效果
2.建议提供功能杀掉手机上执行monkey的功能，杀掉手机中的monkey进程。

**Comment by looklukelu** [comment]
1、现在-s 我随便指定的，你可以fork下，自己改下用
2、测试结束时（测试时长到或按ctrl+C）会停掉monkey logcat进程
