### ISSUE TITLE
没找到upload.py文件，作者可以添加一下吗？

### ISSUE THREAD

**Issue by Leonwenbin** [alibaba/mobileperf#19]
![image](https://user-images.githubusercontent.com/56778345/167160860-e82723ba-610a-408f-9935-3ae8ec4f2715.png)

**Comment by looklukelu** [comment]
不影响运行，自定义实现下上报，并不复杂

**Comment by Leonwenbin** [comment]
> 不影响运行，自定义实现下上报，并不复杂

好的，感谢~
