### ISSUE TITLE
游戏类app的FPS采集到的都是 0

### ISSUE THREAD

**Issue by qintianchen** [alibaba/mobileperf#3]
测试的游戏是Unity引擎开发。另外期待官方的meminfo的新的采集方案。我也觉得dumpsys meminfo性能有很大问题。但是Gamebench对meminfo的采集却感觉对app没有影响，觉得它应该用了什么黑科技吧。

**Comment by looklukelu** [comment]
fps需要在滑动时才有值，静止时是0，前提需排除静止的情况
1、Unity没有测试过，如果不是用的Android那一套绘制，可能获取不到
2、dumpsys meminfo在低端手机上耗时5 6S，中高端手机1s左右，手机配置越来越好，如果官方觉得不是问题，估计不会优化了
