### ISSUE TITLE
(hprof文件是空的)The hprof file is empty

### ISSUE THREAD

**Issue by AnswerZhao** [alibaba/mobileperf#7]
设置了三分钟和monkey，其他数据都有，但是hprof文件是空的。

I config the package, timeout(=3), monkey in the config.conf, but the hprof file is empty, other data of files are normal.

**Comment by looklukelu** [comment]
adb shell后手动试下am dumpheap process_name /data/local/tmp/test.hprof 命令，可能会报securityexception process not debuggable的错误，因为是release包的原因，需要换成debug版本apk再试下

**Comment by AnswerZhao** [comment]
@looklukelu 可以啦，多谢。It works, thanks.
